jetpacker:
  ubuntu:
    name: ubuntu
    label: Ubuntu
    description: Ubuntu is an open source software platform that runs from the cloud, to the smartphone, to all your things.
    releases:
      defaultVersion: ubuntu/trusty64
      versions:
        - ubuntu/trusty32
        - ubuntu/trusty64
      property: { name: ubuntu_image, label: Image }

  openjdk:
    name: openjdk
    label: OpenJDK
    description: OpenJDK (Open Java Development Kit) is a free and open source implementation of the Java Platform, Standard Edition.
    releases:
      defaultVersion: 8
      versions: [ 7, 8 ]
      property: { name: openjdk_version, label: Version }

  node:
    name: node
    label: Node.js
    description: Node.js is a JavaScript runtime built on Chrome's V8 JavaScript engine. Node.js uses an event-driven, non-blocking I/O model that makes it lightweight and efficient. Node.js' package ecosystem, npm, is the largest ecosystem of open source libraries in the world.
    namespace: nodejs
    endpoint: GitHub
    releases:
      property: { name: node_version, label: Version }
    dependency:
      name: nvm
      namespace: creationix
      endpoint: GitHub
      releases:
        property: { name: nvm_version, label: Version }

  guard:
    name: guard
    label: Guard
    description: Guard is a command line tool to easily handle events on file system modifications.
    dependency:
      name: ruby
      namespace: ruby
      endpoint: GitHub
      releases:
        property: { name: ruby_version, label: Version }

  databases:
    - name: mysql
      label: MySQL
      description: MySQL is the most popular Open Source SQL database management system.
      endpoint: DockerHub
      releases:
        property: { name: mysql_version, label: Version }
      volumes:
        - host: '{{ configuration_home }}/mysql'
          container: /etc/mysql/conf.d
        - host: '{{ data_home }}/mysql'
          container: /var/lib/mysql
      publishedPorts:
        - host: '{{ mysql_port }}'
          container: 3306
      environmentVariables:
        MYSQL_ROOT_PASSWORD: '{{ mysql_root_password }}'
        MYSQL_DATABASE: '{{ mysql_database }}'
      properties:
        - { name: mysql_root_password, label: Root Password, value: root }
        - { name: mysql_database, label: Database }
        - { name: mysql_port, label: Port, value: 3306 }

    - name: mariadb
      label: MariaDB
      description: MariaDB is an enhanced, drop-in replacement for MySQL.
      endpoint: DockerHub
      releases:
        property: { name: mariadb_version, label: Version }
      volumes:
        - host: '{{ configuration_home }}/mariadb'
          container: /etc/mysql/conf.d
        - host: '{{ data_home }}/mariadb'
          container: /var/lib/mariadb
      publishedPorts:
        - host: '{{ mariadb_port }}'
          container: 3306
      environmentVariables:
        MYSQL_ROOT_PASSWORD: '{{ mariadb_root_password }}'
        MYSQL_DATABASE: '{{ mariadb_database }}'
      properties:
        - { name: mariadb_root_password, label: Root Password, value: root }
        - { name: mariadb_database, label: Database }
        - { name: mariadb_port, label: Port, value: 3306 }

    - name: postgres
      label: PostgreSQL
      description: PostgreSQL is a powerful, open source object-relational database system.
      endpoint: DockerHub
      releases:
        property: { name: postgres_version, label: Version }
      volumes:
        - host: '{{ data_home }}/postgres'
          container: /var/lib/postgresql/data/pgdata
      publishedPorts:
        - host: '{{ postgres_port }}'
          container: 5432
      environmentVariables:
        POSTGRES_USER: '{{ postgres_user }}'
        POSTGRES_PASSWORD: '{{ postgres_password }}'
        POSTGRES_DB: '{{ postgres_database }}'
        PGDATA : /var/lib/postgresql/data/pgdata
      properties:
        - { name: postgres_user, label: User, value: root }
        - { name: postgres_password, label: Password, value: root }
        - { name: postgres_database, label: Database }
        - { name: postgres_port, label: Port, value: 5432 }

    - name: mongo
      label: MongoDB
      description: MongoDB is an open-source, document database designed for ease of development and scaling.
      endpoint: DockerHub
      releases:
        property: { name: mongo_version, label: Version }
      volumes:
        - host: '{{ data_home }}/mongo'
          container: /data/db
      publishedPorts:
        - host: '{{ mongo_port }}'
          container: 27017
      properties:
        - { name: mongo_port, label: Port, value: 27017 }

    - name: redis
      label: Redis
      description: Redis is an open source (BSD licensed), in-memory data structure store, used as database, cache and message broker.
      endpoint: DockerHub
      releases:
        property: { name: redis_version, label: Version }
      command: redis-server --appendonly yes
      volumes:
        - host: '{{ configuration_home }}/redis'
          container: /usr/local/etc/redis
        - host: '{{ data_home }}/redis'
          container: /data
      publishedPorts:
        - host: '{{ redis_port }}'
          container: 6379
      properties:
        - { name: redis_port, label: Port, value: 6379 }

  messageQueues:
    - name: rabbitmq
      label: RabbitMQ
      description: RabbitMQ is a lightweight, reliable, scalable and portable message broker.
      endpoint: DockerHub
      releases:
        property: { name: rabbitmq_version, label: Version }
      volumes:
        - host: '{{ data_home }}/rabbitmq'
          container: /var/lib/rabbitmq
      publishedPorts:
        - host: '{{ rabbitmq_port }}'
          container: 5672
        - host: '{{ rabbitmq_management_port }}'
          container: 15672
      environmentVariables:
        RABBITMQ_DEFAULT_USER: '{{ rabbitmq_user }}'
        RABBITMQ_DEFAULT_PASS: '{{ rabbitmq_password }}'
        RABBITMQ_NODE_NAME: '{{ rabbitmq_node_name }}'
        RABBITMQ_ERLANG_COOKIE: '{{ rabbitmq_cookie }}'
      properties:
        - { name: rabbitmq_user, label: User, value: rabbitmq }
        - { name: rabbitmq_password, label: Password, value: rabbitmq }
        - { name: rabbitmq_node_name, label: Node Name, value: node@rabbitmq }
        - { name: rabbitmq_cookie, label: Cookie, value: rabbitmq_cookie }
        - { name: rabbitmq_port, label: Port, value: 5672 }
        - { name: rabbitmq_management_port, label: Management Port, value: 15672 }

  searchEngines:
    - name: elasticsearch
      label: ElasticSearch
      description: Elasticsearch is a distributed, open source search and analytics engine, designed for horizontal scalability, reliability, and easy management.
      endpoint: DockerHub
      releases:
        property: { name: elasticsearch_version, label: Version }

    - name: solr
      label: Solr
      description: Solr is the popular, blazing-fast, open source enterprise search platform built on Apache Lucene.
      endpoint: DockerHub
      releases:
        property: { name: solr_version, label: Version }