server:
  port: 5000

spring:
  devtools:
    restart:
      enabled: false
  freemarker:
    cache: false
    template-loader-path: classpath:/freemarker

jetpackr:
  machine:
    name: ubuntu
    label: Ubuntu
    description: Ubuntu is an open source software platform that runs from the cloud, to the smartphone, to all your things.
    box:
      name: box
      label: Box
      options:
        - { label: Ubuntu Xenial Xerus 64, value: ubuntu/xenial64 }
        - { label: Ubuntu Xenial Xerus 32, value: ubuntu/xenial32 }
        - { label: Ubuntu Trusty Tahr 64, value: ubuntu/trusty64 }
        - { label: Ubuntu Trusty Tahr 32, value: ubuntu/trusty32 }
    memory: { name: memory, label: Memory (MB), value: 4096 }
    timezone: { name: timezone, label: Timezone }
    synchronization:
      name: synchronization
      label: Synchronization
      options:
        - { label: Guard, value: guard }
        - { label: Rsync, value: rsync }
    guard:
      name: guard
      label: Guard
      description: Guard is a command line tool to easily handle events on file system modifications.
      install: { name: install, label: Install Guard }
      dependency:
        name: ruby
        label: Ruby
        repository:
          type: GitHub
          url: https://api.github.com/repos/ruby/ruby/tags
        version: { name: version, label: Version }

  kits:
    jdk:
      name: jdk
      label: JDK
      description: JDK (Java Development Kit) is a popular platform for development and deployment of portable applications for desktop and server environments.
      repository:
        type: SDKMAN
        url: https://api.sdkman.io/2/candidates
      version:
        name: version
        label: Version
      install: { name: install, label: Install JDK, value: true }

    node:
      name: node
      label: Node.js
      description: Node.js is a JavaScript runtime built on Chrome's V8 JavaScript engine. Node.js uses an event-driven, non-blocking I/O model that makes it lightweight and efficient. Node.js' package ecosystem, npm, is the largest ecosystem of open source libraries in the world.
      repository:
        type: GitHub
        url: https://api.github.com/repos/nodejs/node/tags
      version: { name: version, label: Version }
      install: { name: install, label: Install Node.js }
      dependency:
        name: nvm
        label: Node Version Manager
        repository:
          type: GitHub
          url: https://api.github.com/repos/creationix/nvm/tags
        version: { name: version, label: Version }
      extensions:
        - name: angular-cli
          alias: '@angular/cli'
          label: Angular CLI
          description: Angular is a development platform for building mobile and desktop web applications using Typescript/JavaScript (JS) and other languages.
          repository:
            type: GitHub
            url: https://api.github.com/repos/angular/angular-cli/tags
          version: { name: version, label: Version }
        - name: aurelia-cli
          label: Aurelia CLI
          description: Aurelia is a JavaScript client framework for mobile, desktop and web leveraging simple conventions and empowering creativity.
          repository:
            type: NPMRegistry
            url: https://registry.npmjs.com/aurelia-cli # https://api.github.com/repos/aurelia/cli/tags
          version: { name: version, label: Version }
        - name: ember-cli
          label: Ember.js CLI
          description: Ember.js is a Javascript framework that greatly reduces the time, effort and resources needed to build any web application.
          repository:
            type: NPMRegistry
            url: https://registry.npmjs.com/ember-cli # https://api.github.com/repos/ember-cli/ember-cli/tags
          version: { name: version, label: Version }
        - name: create-react-app
          label: React CLI
          description: React is a declarative, efficient, and flexible JavaScript library for building user interfaces.
          repository:
            type: NPMRegistry
            url: https://registry.npmjs.com/create-react-app
          version: { name: version, label: Version }
        - name: vue-cli
          label: Vue.js CLI
          description: Vue.js is a library for building interactive web interfaces. It provides data-reactive components with a simple and flexible API.
          repository:
            type: NPMRegistry
            url: https://registry.npmjs.com/vue-cli # https://api.github.com/repos/vuejs/vue-cli/tags
          version: { name: version, label: Version }

  containers:
    # data stores
    mysql:
      name: mysql
      label: MySQL
      description: MySQL is the most popular Open Source SQL database management system.
      type: DataStore
      repository:
        type: DockerHub
        url: https://registry.hub.docker.com/v2/repositories/library/mysql/tags
      version: { name: version, label: Version }
      install: { name: install, label: Install MySQL }
      volumes:
        mysql_conf: /etc/mysql/conf.d
        mysql_data: /var/lib/mysql
      ports:
        - host: 3306
          container: 3306
      parameters:
        - { name: MYSQL_ROOT_PASSWORD, label: Root Password, value: root }
        - { name: MYSQL_DATABASE, label: Database, value: my_database }
        - { name: MYSQL_USER, label: Database User, value: user }
        - { name: MYSQL_PASSWORD, label: Database Password, value: password }

    mariadb:
      name: mariadb
      label: MariaDB
      description: MariaDB is an enhanced, drop-in replacement for MySQL.
      type: DataStore
      repository:
        type: DockerHub
        url: https://registry.hub.docker.com/v2/repositories/library/mariadb/tags
      version: { name: version, label: Version }
      install: { name: install, label: Install MariaDB }
      volumes:
        mariadb_conf: /etc/mysql/conf.d
        mariadb_data: /var/lib/mariadb
      ports:
        - host: 3306
          container: 3306
      parameters:
        - { name: MYSQL_ROOT_PASSWORD, label: Root Password, value: root }
        - { name: MYSQL_DATABASE, label: Database, value: my_database }
        - { name: MYSQL_USER, label: Database User, value: user }
        - { name: MYSQL_PASSWORD, label: Database Password, value: password }

    postgres:
      name: postgres
      label: PostgreSQL
      description: PostgreSQL is a powerful, open source object-relational database system.
      type: DataStore
      repository:
        type: DockerHub
        url: https://registry.hub.docker.com/v2/repositories/library/postgres/tags
      version: { name: version, label: Version }
      install: { name: install, label: Install PostgreSQL }
      volumes:
        postgres_data: /var/lib/postgresql/data/pgdata
      ports:
        - host: 5432
          container: 5432
      environment:
        PGDATA: /var/lib/postgresql/data/pgdata
      parameters:
        - { name: POSTGRES_USER, label: User, value: root }
        - { name: POSTGRES_PASSWORD, label: Password, value: root }
        - { name: POSTGRES_DB, label: Database, value: my_database }

    mongo:
      name: mongo
      label: MongoDB
      description: MongoDB is an open-source, document database designed for ease of development and scaling.
      type: DataStore
      repository:
        type: DockerHub
        url: https://registry.hub.docker.com/v2/repositories/library/mongo/tags
      version: { name: version, label: Version }
      install: { name: install, label: Install MongoDB }
      volumes:
        mongo_data: /data/db
      ports:
        - host: 27017
          container: 27017

    redis:
      name: redis
      label: Redis
      description: Redis is an open source (BSD licensed), in-memory data structure store, used as database, cache and message broker.
      type: DataStore
      repository:
        type: DockerHub
        url: https://registry.hub.docker.com/v2/repositories/library/redis/tags
      version: { name: version, label: Version }
      install: { name: install, label: Install Redis }
      command: redis-server --appendonly yes
      volumes:
        redis_conf: /usr/local/etc/redis
        redis_data: /data
      ports:
        - host: 6379
          container: 6379

    # message brokers
    rabbitmq:
      name: rabbitmq
      label: RabbitMQ
      description: RabbitMQ is a lightweight, reliable, scalable and portable message broker.
      type: MessageBroker
      repository:
        type: DockerHub
        url: https://registry.hub.docker.com/v2/repositories/library/rabbitmq/tags
      version: { name: version, label: Version }
      install: { name: install, label: Install RabbitMQ }
      volumes:
        rabbitmq_conf: /etc/rabbitmq
        rabbitmq_data: /var/lib/rabbitmq
      ports:
        - host: 5672
          container: 5672
      parameters:
        - { name: RABBITMQ_DEFAULT_USER, label: User, value: rabbitmq }
        - { name: RABBITMQ_DEFAULT_PASS, label: Password, value: rabbitmq }
        - { name: RABBITMQ_NODE_NAME, label: Node Name, value: node@rabbitmq }
        - { name: RABBITMQ_ERLANG_COOKIE, label: Erlang Cookie, value: rabbitmq_erlang_cookie }

    eclipse-mosquitto:
      name: eclipse-mosquitto
      label: Eclipse Mosquitto
      description: Eclipse Mosquitto is an open source message broker which implements MQTT version 3.1 and 3.1.1
      type: MessageBroker
      repository:
        type: DockerHub
        url: https://registry.hub.docker.com/v2/repositories/library/eclipse-mosquitto/tags
      version: { name: version, label: Version }
      install: { name: install, label: Install RabbitMQ }
      volumes:
        eclipse-mosquitto_conf: /mosquitto/config
        eclipse-mosquitto_data: /mosquitto/data
        eclipse-mosquitto_log: /mosquitto/log
      ports:
        - host: 1883
          container: 1883
        - host: 9001
          container: 9001

#repository:
#  type: GitHub
#  url: http://api.github.com/

    # search engines
    elasticsearch:
      name: elasticsearch
      label: ElasticSearch
      description: Elasticsearch is a distributed, open source search and analytics engine, designed for horizontal scalability, reliability, and easy management.
      type: SearchEngine
      # To be switched to https://api.github.com/repos/elastic/elasticsearch-docker/branches
      # docker_url = docker.elastic.co/elasticsearch
      # consider using repository { type: DockerHub, url: http://docker.com/etc }
      repository:
        type: DockerHub
        url: https://registry.hub.docker.com/v2/repositories/library/elasticsearch/tags
      version: { name: version, label: Version }
      install: { name: install, label: Install ElasticSearch }
      volumes:
        elasticsearch_conf: /usr/share/elasticsearch/config
        elasticsearch_data: /usr/share/elasticsearch/data
      ports:
        - host: 9200
          container: 9200

    solr:
      name: solr
      label: Solr
      description: Solr is the popular, blazing-fast, open source enterprise search platform built on Apache Lucene.
      type: SearchEngine
      repository:
        type: DockerHub
        url: https://registry.hub.docker.com/v2/repositories/library/solr/tags
      version: { name: version, label: Version }
      install: { name: install, label: Install Solr }
      volumes:
        solr_data: /opt/solr/server/solr/mycores
      ports:
        - host: 8983
          container: 8983

  templates:
    basic:
      files:
        - /roles/applications/tasks/main.yml.ftl
        - /roles/commons/handlers/main.yml.ftl
        - /roles/commons/tasks/main.yml.ftl
        - /roles/commons/vars/main.yml.ftl
        - /workspace/workspace.yml.ftl
        - /Vagrantfile.ftl
        - /playbook.yml.ftl
    docker:
      files:
        - /roles/docker/tasks/main.yml.ftl
        - /workspace/docker-compose.yml.ftl
    guard:
      files:
        - /roles/guard/tasks/main.yml.ftl
        - /workspace/Gemfile.ftl
        - /workspace/Guardfile.ftl
    jdk:
      files:
        - /roles/jdk/tasks/main.yml.ftl
        - /roles/jdk/tasks/sdkman_candidate.yml.ftl
    node:
      files:
        - /roles/node/tasks/main.yml.ftl
        - /roles/node/tasks/npm_module.yml.ftl
        - /roles/node/tasks/bind_mount_node_modules.yml.ftl