jetpacker:
  boxes:
    - name: ubuntu
      description: Ubuntu is an open source software platform that runs from the cloud, to the smartphone, to all your things.
      tab:
        index: 0
        label: Ubuntu
      releases:
        defaultVersion: ubuntu/trusty64
        versions:
          - ubuntu/trusty32
          - ubuntu/trusty64

  kits:
    - name: openjdk
      description: OpenJDK (Open Java Development Kit) is a free and open source implementation of the Java Platform, Standard Edition.
      releases:
        defaultVersion: 8
        versions: [ 7, 8 ]
      tab:
        index: 0
        label: Java

    - name: node
      description: Node.js is a JavaScript runtime built on Chrome's V8 JavaScript engine. Node.js uses an event-driven, non-blocking I/O model that makes it lightweight and efficient. Node.js' package ecosystem, npm, is the largest ecosystem of open source libraries in the world.
      namespace: nodejs
      endpoint: GitHub
      tab:
        index: 2
        label: Node.js
      dependency:
        name: nvm
        namespace: creationix
        endpoint: GitHub

    - name: guard
      description: Guard is a command line tool to easily handle events on file system modifications.
      namespace: guard
      endpoint: None
      tab:
        index: 3
        label: Guard
      dependency:
        name: ruby
        namespace: ruby
        endpoint: GitHub

  databases:
    - name: mysql
      description: MySQL is the most popular Open Source SQL database management system.
      endpoint: DockerHub
      tab:
        index: 0
        label: MySQL
      volumes:
        - host: '{{ configuration_home }}/mysql'
          container: /etc/mysql/conf.d
        - host: '{{ data_home }}/mysql'
          container: /var/lib/mysql
      publishedPorts:
        - host: :mysql_port
          container: 3306
      environmentVariables:
        MYSQL_ROOT_PASSWORD: :mysql_root_password
        MYSQL_DATABASE: :mysql_database
      properties:
        - { name: mysql_root_password, label: Root Password, value: root }
        - { name: mysql_database, label: Database, value: null }
        - { name: mysql_port, label: Port, value: 3306 }

    - name: mariadb
      description: MariaDB is an enhanced, drop-in replacement for MySQL.
      endpoint: DockerHub
      tab:
        index: 1
        label: MariaDB
      volumes:
        - host: '{{ configuration_home }}/mariadb'
          container: /etc/mysql/conf.d
        - host: '{{ data_home }}/mariadb'
          container: /var/lib/mariadb
      publishedPorts:
        - host: :mariadb_port
          container: 3306
      environmentVariables:
        MYSQL_ROOT_PASSWORD: :mariadb_root_password
        MYSQL_DATABASE: :mariadb_database
      properties:
        - { name: mariadb_root_password, label: Root Password, value: root }
        - { name: mariadb_database, label: Database, value: null }
        - { name: mariadb_port, label: Port, value: 3306 }

    - name: postgres
      description: PostgreSQL is a powerful, open source object-relational database system.
      endpoint: DockerHub
      tab:
        index: 2
        label: PostgreSQL
      volumes:
        - host: '{{ data_home }}/postgres'
          container: /var/lib/postgresql/data/pgdata
      publishedPorts:
        - host: :postgres_port
          container: 5432
      environmentVariables:
        POSTGRES_USER: :postgres_user
        POSTGRES_PASSWORD: :postgres_password
        POSTGRES_DB: :postgres_database
        PGDATA : /var/lib/postgresql/data/pgdata
      properties:
        - { name: postgres_user, label: User, value: root }
        - { name: postgres_password, label: Password, value: root }
        - { name: postgres_database, label: Database, value: null }
        - { name: postgres_port, label: Port, value: 5432 }

    - name: mongo
      description: MongoDB is an open-source, document database designed for ease of development and scaling.
      endpoint: DockerHub
      tab:
        index: 3
        label: MongoDB
      volumes:
        - host: '{{ data_home }}/mongo'
          container: /data/db
      publishedPorts:
        - host: :mongo_port
          container: 27017
      properties:
        - { name: mongo_port, label: Port, value: 27017 }

    - name: redis
      description: Redis is an open source (BSD licensed), in-memory data structure store, used as database, cache and message broker.
      endpoint: DockerHub
      tab:
        index: 4
        label: Redis
      command: redis-server --appendonly yes
      volumes:
        - host: '{{ configuration_home }}/redis'
          container: /usr/local/etc/redis
        - host: '{{ data_home }}/redis'
          container: /data
      publishedPorts:
        - host: :redis_port
          container: 6379
      properties:
        - { name: redis_port, label: Port, value: 6379 }

  messageQueues:
    - name: rabbitmq
      description: RabbitMQ is a lightweight, reliable, scalable and portable message broker.
      endpoint: DockerHub
      tab:
        index: 0
        label: RabbitMQ
      volumes:
        - host: '{{ data_home }}/rabbitmq'
          container: /var/lib/rabbitmq
      publishedPorts:
        - host: :rabbitmq_port
          container: 5672
        - host: :rabbitmq_management_port
          container: 15672
      environmentVariables:
        RABBITMQ_DEFAULT_USER: :rabbitmq_user
        RABBITMQ_DEFAULT_PASS: :rabbitmq_password
        RABBITMQ_NODE_NAME: :rabbitmq_node_name
        RABBITMQ_ERLANG_COOKIE: :rabbitmq_cookie
      properties:
        - { name: rabbitmq_user, label: User, value: rabbitmq }
        - { name: rabbitmq_password, label: Password, value: rabbitmq }
        - { name: rabbitmq_node_name, label: Node Name, value: node@rabbitmq }
        - { name: rabbitmq_cookie, label: Cookie, value: rabbitmq_cookie }
        - { name: rabbitmq_port, label: Port, value: 5672 }
        - { name: rabbitmq_management_port, label: Management Port, value: 15672 }

  searchEngines:
    - name: elasticsearch
      description: Elasticsearch is a distributed, open source search and analytics engine, designed for horizontal scalability, reliability, and easy management.
      endpoint: DockerHub
      tab:
        index: 0
        label: Elasticsearch

    - name: solr
      description: Solr is the popular, blazing-fast, open source enterprise search platform built on Apache Lucene.
      endpoint: DockerHub
      tab:
        index: 1
        label: Solr
