server:
  port: 5000

jetpacker:
  machine:
    name: ubuntu
    label: Ubuntu
    description: Ubuntu is an open source software platform that runs from the cloud, to the smartphone, to all your things.
    box:
      name: box
      label: Box
      options:
        - { label: Ubuntu Trusty Tahr 64, value: ubuntu/trusty64 }
        - { label: Ubuntu Trusty Tahr 32, value: ubuntu/trusty32 }
    memory: { name: memory, label: Memory (MB), value: 4096 }
    timezone: { name: timezone, label: Timezone }

  kits:
    openjdk:
      name: openjdk
      label: OpenJDK
      description: OpenJDK (Open Java Development Kit) is a free and open source implementation of the Java Platform, Standard Edition.
      repository: SdkMan
      version:
        name: version
        label: Version
        options:
        - { label: 8, value: openjdk-8-jdk }
        - { label: 7, value: openjdk-7-jdk }
      install: { name: install, label: Install OpenJDK, value: true }

    node:
      name: node
      namespace: nodejs
      label: Node.js
      description: Node.js is a JavaScript runtime built on Chrome's V8 JavaScript engine. Node.js uses an event-driven, non-blocking I/O model that makes it lightweight and efficient. Node.js' package ecosystem, npm, is the largest ecosystem of open source libraries in the world.
      repository: GitHub
      version: { name: version, label: Version }
      install: { name: install, label: Install Node.js }
      dependency:
        name: nvm
        namespace: creationix
        label: Node Version Manager
        repository: GitHub
        version: { name: version, label: Version }
      extensions:
        - name: angular-cli
          namespace: angular
          label: Angular CLI
          description: Angular is a development platform for building mobile and desktop web applications using Typescript/JavaScript (JS) and other languages.
          repository: GitHub
          version: { name: version, label: Version }
        - name: aurelia-cli
          alias: cli
          namespace: aurelia
          label: Aurelia CLI
          description: Aurelia is a JavaScript client framework for mobile, desktop and web leveraging simple conventions and empowering creativity.
          repository: GitHub
          version: { name: version, label: Version }
        - name: ember-cli
          namespace: ember-cli
          label: Ember.js CLI
          description: Ember.js is a Javascript framework that greatly reduces the time, effort and resources needed to build any web application.
          repository: GitHub
          version: { name: version, label: Version }
        - name: create-react-app
          namespace: facebookincubator
          label: React CLI
          description: React is a declarative, efficient, and flexible JavaScript library for building user interfaces.
          repository: GitHub
          version: { name: version, label: Version }
        - name: vue-cli
          namespace: vuejs
          label: Vue.js CLI
          description: Vue.js is a library for building interactive web interfaces. It provides data-reactive components with a simple and flexible API.
          repository: GitHub
          version: { name: version, label: Version }

    guard:
      name: guard
      label: Guard
      description: Guard is a command line tool to easily handle events on file system modifications.
      install: { name: install, label: Install Guard }
      dependency:
        name: ruby
        namespace: ruby
        label: Ruby
        repository: GitHub
        version: { name: version, label: Version }

  containers:
    # data stores
    mysql:
      name: mysql
      label: MySQL
      description: MySQL is the most popular Open Source SQL database management system.
      type: DataStore
      repository: DockerHub
      version: { name: version, label: Version }
      install: { name: install, label: Install MySQL }
      volumes:
        - host: /home/vagrant/configuration/mysql
          container: /etc/mysql/conf.d
        - host: /home/vagrant/data/mysql
          container: /var/lib/mysql
      ports:
        - host: 3306
          container: 3306
      parameters:
        - { name: MYSQL_ROOT_PASSWORD, label: Root Password, value: root }
        - { name: MYSQL_DATABASE, label: Database, value: my_database }

    mariadb:
      name: mariadb
      label: MariaDB
      description: MariaDB is an enhanced, drop-in replacement for MySQL.
      type: DataStore
      repository: DockerHub
      version: { name: version, label: Version }
      install: { name: install, label: Install MariaDB }
      volumes:
        - host: /home/vagrant/configuration/mariadb
          container: /etc/mysql/conf.d
        - host: /home/vagrant/data/mariadb
          container: /var/lib/mariadb
      ports:
        - host: 3306
          container: 3306
      parameters:
        - { name: MYSQL_ROOT_PASSWORD, label: Root Password, value: root }
        - { name: MYSQL_DATABASE, label: Database, value: my_database }

    postgres:
      name: postgres
      label: PostgreSQL
      description: PostgreSQL is a powerful, open source object-relational database system.
      type: DataStore
      repository: DockerHub
      version: { name: version, label: Version }
      install: { name: install, label: Install PostgreSQL }
      volumes:
        - host: /home/vagrant/configuration/postgres
          container: /var/lib/postgresql/data/pgdata
      ports:
        - host: 5432
          container: 5432
      env:
        PGDATA: /var/lib/postgresql/data/pgdata
      parameters:
        - { name: POSTGRES_USER, label: User, value: root }
        - { name: POSTGRES_PASSWORD, label: Password, value: root }
        - { name: POSTGRES_DB, label: Database, value: my_database }

    mongo:
      name: mongo
      label: MongoDB
      description: MongoDB is an open-source, document database designed for ease of development and scaling.
      type: DataStore
      repository: DockerHub
      version: { name: version, label: Version }
      install: { name: install, label: Install MongoDB }
      volumes:
        - host: /home/vagrant/data/mongo
          container: /data/db
      ports:
        - host: 27017
          container: 27017

    redis:
      name: redis
      label: Redis
      description: Redis is an open source (BSD licensed), in-memory data structure store, used as database, cache and message broker.
      type: DataStore
      repository: DockerHub
      version: { name: version, label: Version }
      install: { name: install, label: Install Redis }
      command: redis-server --appendonly yes
      volumes:
        - host: /home/vagrant/configuration/redis
          container: /usr/local/etc/redis
        - host: /home/vagrant/data/redis
          container: /data
      ports:
        - host: 6379
          container: 6379

    # message brokers
    rabbitmq:
      name: rabbitmq
      label: RabbitMQ
      description: RabbitMQ is a lightweight, reliable, scalable and portable message broker.
      type: MessageBroker
      repository: DockerHub
      version: { name: version, label: Version }
      install: { name: install, label: Install RabbitMQ }
      volumes:
        - host: /home/vagrant/data/rabbitmq
          container: /var/lib/rabbitmq
      ports:
        - host: 5672
          container: 5672
      parameters:
        - { name: RABBITMQ_DEFAULT_USER, label: User, value: rabbitmq }
        - { name: RABBITMQ_DEFAULT_PASS, label: Password, value: rabbitmq }
        - { name: RABBITMQ_NODE_NAME, label: Node Name, value: node@rabbitmq }
        - { name: RABBITMQ_ERLANG_COOKIE, label: Erlang Cookie, value: rabbitmq_erlang_cookie }

    # search engines
    elasticsearch:
      name: elasticsearch
      label: ElasticSearch
      description: Elasticsearch is a distributed, open source search and analytics engine, designed for horizontal scalability, reliability, and easy management.
      type: SearchEngine
      repository: DockerHub
      version: { name: version, label: Version }
      install: { name: install, label: Install ElasticSearch }
      ports:
        - host: 9200
          container: 9200

    solr:
      name: solr
      label: Solr
      description: Solr is the popular, blazing-fast, open source enterprise search platform built on Apache Lucene.
      type: SearchEngine
      repository: DockerHub
      version: { name: version, label: Version }
      install: { name: install, label: Install Solr }
      ports:
        - host: 8983
          container: 8983