jetpacker:
  boxes:
    - name: ubuntu
      description: Ubuntu is an open source software platform that runs from the cloud, to the smartphone, to all your things.
      tab:
        index: 0
        label: Ubuntu
      releases:
        defaultVersion: ubuntu/trusty64
        versions:
          - ubuntu/trusty32
          - ubuntu/trusty64

  kits:
    - name: openjdk
      description: OpenJDK (Open Java Development Kit) is a free and open source implementation of the Java Platform, Standard Edition.
      releases:
        defaultVersion: 8
        versions: [ 7, 8 ]
      tab:
        index: 0
        label: Java

    - name: node
      description: Node.js is a JavaScript runtime built on Chrome's V8 JavaScript engine. Node.js uses an event-driven, non-blocking I/O model that makes it lightweight and efficient. Node.js' package ecosystem, npm, is the largest ecosystem of open source libraries in the world.
      namespace: nodejs
      endpoint: GitHub
      tab:
        index: 2
        label: Node.js
      dependency:
        name: nvm
        namespace: creationix
        endpoint: GitHub

    - name: guard
      description: Guard is a command line tool to easily handle events on file system modifications.
      namespace: guard
      endpoint: None
      tab:
        index: 3
        label: Guard
      dependency:
        name: ruby
        namespace: ruby
        endpoint: GitHub

  databases:
    - name: mysql
      description: MySQL is the most popular Open Source SQL database management system.
      endpoint: DockerHub
      tab:
        index: 0
        label: MySQL
      volumes:
        /etc/mysql/conf.d: &mysql_configuration_home
        /var/lib/mysql: &mysql_data_home
      published_ports:
        - host: &mysql_port
          container: 3306
      environment_variables:
        MYSQL_ROOT_PASSWORD: &mysql_root_password
        MYSQL_DATABASE: &mysql_database

    - name: mariadb
      description: MariaDB is an enhanced, drop-in replacement for MySQL.
      endpoint: DockerHub
      tab:
        index: 1
        label: MariaDB
      volumes:
        /etc/mysql/conf.d: &mariadb_configuration_home
        /var/lib/mysql: &mariadb_data_home
      published_ports:
        - host: &mariadb_port
          container: 3306
      environment_variables:
        MYSQL_ROOT_PASSWORD: &mariadb_root_password
        MYSQL_DATABASE: &mariadb_database

    - name: postgres
      description: PostgreSQL is a powerful, open source object-relational database system.
      endpoint: DockerHub
      tab:
        index: 2
        label: PostgreSQL
      volumes:
        /var/lib/postgresql/data/pgdata: &postgres_data_home
      published_ports:
        - host: &postgres_port
          container: 5432
      environment_variables:
        POSTGRES_USER: &postgres_user
        POSTGRES_PASSWORD: &postgres_password
        POSTGRES_DB: &postgres_database
        PGDATA : /var/lib/postgresql/data/pgdata

    - name: mongo
      description: MongoDB is an open-source, document database designed for ease of development and scaling.
      endpoint: DockerHub
      tab:
        index: 3
        label: MongoDB
      volumes:
        /data/db: &mongo_data_home
      published_ports:
        - host: &mongo_port
          container: 27017

    - name: redis
      description: Redis is an open source (BSD licensed), in-memory data structure store, used as database, cache and message broker.
      endpoint: DockerHub
      tab:
        index: 4
        label: Redis
      command: redis-server --appendonly yes
      volumes:
        /usr/local/etc/redis: &redis_configuration_home
        /data: &redis_data_home
      published_ports:
        - host: &redis_port
          container: 6379

  messageQueues:
    - name: rabbitmq
      description: RabbitMQ is a lightweight, reliable, scalable and portable message broker.
      endpoint: DockerHub
      properties:
        - { name: rabbitmq_user, label: User, value: rabbitmq }
        - { name: rabbitmq_password, label: Password, value: rabbitmq }
        - { name: rabbitmq_node_name, label: Node name, value: rabbitmq }
        - { name: rabbitmq_cookie, label: Cookie, value: rabbitmq }
        - { name: rabbitmq_data_home, label: Data directory, value: rabbitmq, prefix: '{{ data_home }}/' }
        - { name: rabbitmq_port, label: Port, value: 5672 }
        - { name: rabbitmq_management_port, label: Management Port, value: 15672 }
      tab:
        index: 0
        label: RabbitMQ
      volumes:
        /var/lib/rabbitmq: &rabbitmq_data_home
      published_ports:
        - host: &rabbitmq_port
          container: 5672
        - host: &rabbitmq_management_port
          container: 15672
      environment_variables:
        RABBITMQ_DEFAULT_USER: &rabbitmq_user
        RABBITMQ_DEFAULT_PASS: &rabbitmq_password
        RABBITMQ_NODE_NAME: &rabbitmq_node_name
        RABBITMQ_ERLANG_COOKIE: &rabbitmq_cookie

  searchEngines:
    - name: elasticsearch
      description: Elasticsearch is a distributed, open source search and analytics engine, designed for horizontal scalability, reliability, and easy management.
      endpoint: DockerHub
      tab:
        index: 0
        label: Elasticsearch

    - name: solr
      description: Solr is the popular, blazing-fast, open source enterprise search platform built on Apache Lucene.
      endpoint: DockerHub
      tab:
        index: 1
        label: Solr
