#jinja2: trim_blocks: True, lstrip_blocks: True
-- This file was generated by Ansible. Do not modify directly!

settings {
    logfile = "{{ lsyncd.logDir | mandatory }}/{{ lsyncd.logFile | mandatory }}",
    statusFile = "{{ lsyncd.logDir | mandatory }}/{{ lsyncd.statusFile | mandatory }}",
    insist = true,
    nodaemon = false
}
{% for sync in lsyncd.syncs %}

sync {
    default.rsync,
    source = "{{ sync.source | mandatory }}",
    target = "{{ sync.target | mandatory }}",
    {% if sync.excludes is defined %}
    exclude = { {% for exclude in sync.excludes %}'{{ exclude }}'{% if not loop.last %},{% endif %}{% endfor %} }
    {% endif %}
}
{% endfor %}